---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-observability

configMapGenerator:
  - name: app-config
    files:
      - config/application.yml
    options:
      disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - svc.yaml
  - route.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
