apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tracing-ui
  namespace: openshift-tempo
spec:
  port:
    targetPort: jaeger-ui
  to:
    kind: Service
    name: tempo-sample-query-frontend
  wildcardPolicy: None