---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: bookinfo-app
  name: bookinfo-app
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/applications/bookinfo
    repoURL: https://github.com/anmiralles/openshift-observability-workshop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
