---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/cluster-services/grafana
    repoURL: https://github.com/anmiralles/openshift-observability-workshop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
